name: gtf_to_refflat
description: generate gene annotations in refFlat form
  - gtftorefflat
tools:
  - gtf_to_refflat:
      description: generate gene annotations in refFlat form
      homepage: https://pachterlab.github.io/kallisto/
      documentation: https://pachterlab.github.io/kallisto/manual
      tool_dev_url: https://github.com/pachterlab/kallisto
      doi: ""
      licence: ["BSD-2-Clause"]

input:
  - fasta:
      type: file
      description: genome fasta file
      pattern: "*.{fasta*}"
  - reference:
      type: directory
      description: Path to kallisto index
      pattern: "*"

output:
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  - fusions:
      type: file
      description: fusions
      pattern: "*.txt"

authors:
  - "@rannick"
