name: picard_collectrnaseqmetrics
description: Produces RNA alignment metrics for a SAM or BAM file.
keywords:
  - alignment
  - metrics
  - statistics
  - quality
  - bam
  - RNA
tools:
  - picard:
      description: |
        A set of command line tools (in Java) for manipulating high-throughput sequencing (HTS)
        data and formats such as SAM/BAM/CRAM and VCF.
      homepage: https://broadinstitute.github.io/picard/
      documentation: https://broadinstitute.github.io/picard/
      licence: ["MIT"]
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - bam:
      type: file
      description: BAM file
      pattern: "*.{bam}"
  - bai:
      type: file
      description: An optional BAM index file. If desired, --CREATE_INDEX must be passed as a flag
      pattern: "*.{bai}"
  - refflat:
      type: file
      description: Gene annotations in refFlat form
  - rrna_interval:
      type: file
      description: Location of rRNA sequences in genome, in interval_list format
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - metrics:
      type: file
      description: Alignment metrics files generated by picard
      pattern: "*_{metrics}"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@rannick"
