FROM nfcore/test-datasets:rnafusion

LABEL authors="rickard.hammaren@scilifelab.se, phil.ewels@scilifelab.se, martin.proks@scilifelab.se" \
    description="Docker image containing all requirements for nfcore/rnafusion-test container"

ENV USER travis-ci-test

COPY environment.yml /
RUN conda env create -f /environment.yml && conda clean -a
ENV PATH /opt/conda/envs/fusion-inspector/bin:$PATH

WORKDIR /data/
RUN conda config --prepend channels conda-forge && conda config --prepend channels bioconda
RUN conda install --name fusion-inspector hmmer blast gmap star samtools \
                            perl perl-set-intervaltree perl-uri perl-json-xs perl-db-file perl-perlio-gzip perl-carp
RUN hmmpress Pfam-A.hmm
ENV PATH /opt/conda/envs/fusion-inspector/share/fusion-inspector-1.3.1-1/FusionFilter:$PATH
RUN sed -i -e 's/my $CPU = 4;/my $CPU = 2;/' /opt/conda/envs/fusion-inspector/share/fusion-inspector-1.3.1-1/FusionFilter/prep_genome_lib.pl
RUN prep_genome_lib.pl --genome_fa genome.fa --gtf annotation.gtf --pfarm_db Pfam-A.hmm

# Install nextflow
WORKDIR /
RUN curl -s https://get.nextflow.io | bash
RUN chmod +x ./nextflow && mv nextflow /usr/local/bin