name: squid
description: Squid detection of fusions.
keywords:
  - fusion
  - pizzly
tools:
  - pizzly:
      description: Fusion detection using squid
      homepage: https://github.com/Kingsford-Group/squid
      documentation: https://github.com/Kingsford-Group/squid
      tool_dev_url: https://github.com/Kingsford-Group/squid
      doi: ""
      licence: ["BSD-3-Clause"]

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - bam:
      type: file
      description: BAM/CRAM/SAM file
      pattern: "*.{bam,cram,sam}"
  - chimeric_bam:
      type: file
      description: BAM/CRAM/SAM file containing only chimeric sorted reads
      pattern: "*.{bam,cram,sam}"

output:
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  - fusions:
      type: directory
      description: Path to squid fusions
      pattern: "*.txt"

authors:
  - "@rannick"
