#!/bin/bash

cat > Dockerfile <<EOF
# This Dockerfile was generated by tools/build.sh
FROM nfcore/base

LABEL authors="rickard.hammaren@scilifelab.se, phil.ewels@scilifelab.se, martin.proks@scilifelab.se" \\
    description="Docker image containing all requirements for NGI-RNAfusion pipeline"

COPY environment.yml /
COPY tools /tools/

RUN conda env create -f /environment.yml && conda clean -a
EOF

DOCKERFILE=''
for tool in */; do
    for requirements in $tool*; do
        extension=`echo ${requirements##*.}`
        if [ $extension == "yml" ]
        then
            echo "RUN conda env create -f /tools/${requirements} && conda clean -a" >> Dockerfile
        else
            DOCKERFILE+=$"# ${tool%/}\n"
            DOCKERFILE+=$(cat $requirements)
        fi
    done
done

echo "ENV PATH /opt/conda/envs/nf-core-rnafusion-1.0dev/bin:\${PATH}" >> Dockerfile
echo $"\n${DOCKERFILE}" >> Dockerfile
mv Dockerfile ../
